language: node_js
node_js:
- node
- 6
deploy:
  email: al@builtbybrayne.com
  provider: npm
  api_key:
    secure: c1Tk7OXLaH7HJDks4Zsn478F4bogL2EYY0VpI3E+nB+JjjQGOgS3HTyeIbwoqdF3Rejul09zNR4pWl2kBY/V7bHXd47dZgCxHcVSun1F8IPjIt8KenTIaxH3Hn1OcU7PSz2SSfBh/lh7PXiUNi8F8M4w+9ve3QP0lvakOpX4nJCLJc6aqCPX6/hDg2ajGpAaxmDlmC0qoUeqhjDhEySGJkomFce2ZBt50ch6k5d+sO0GbOZZ08EWyPgWXvmwv0YnGpDsmpeA75XIa3guYryEXYHz6ZoiIp+jahyI5MmfIX8owtFMBOLULf/3gHAxuY/k2HYCvl+hTztrqdSFcGRSyhThOjmIF0cWUZ/519fjlBviwIrm4wcTYK2TLDb6IrxXbYCdTR2FPMnoQvAFhDWE2m8bFOM2vWiX0vg8eJaSeIgsGsFwTzL3spigsEeKtgOV6NUCwTwd/SmpCTEmzXY+cEvX8ZbIdfO8WRbDgvUpsEZv9bOHXsReFQ7mTW7Ekov0Ik7i3tMJHnppimgrtIR9AdUz9mCHoI65KwZlSvzcfdSoFXBzdwG0nfQA2Am/0pliY+0KN0hTweXduiLH+3Y1ORxyzm/e84iLTMQASdH4AtMZNUhi2ZDgkqx8Zr2k+TS61dX4Cfyd7yge/s4ed2p3ENZ2IMGDFoVEninnHx0odtg=
  on:
    tags: true
notifications:
  slack:
    secure: NyFqNxdLsFsBtVuB4RztiU5IuLU1+1kLxhBBxFeMjdHQGd/PHuKhkRP7mxCImjaIr3r07p62GPpIeaBQfYJHnKveZm++7U8DFUwzTNu7jKH7wSmC1cg0ZDUlVWZzSDTaMnozu0BQVTNBNpDkie4HddRuexR77YiA1hpdkHFAFN/VFNLZHi+W7ysDXbBObspFhoWu6ou6yZ6B7IAlbbJSrNsGgEkVBe4QjrNc5hWoXoUn6EZ060UyRU68Gi8CYto45w8zyv6RuM68XPCg3+VtHmsTKjfxiFoqXJmNSSUvqOEMg+j+Z72XXsC7jKHoc68lbEsuaTxXIWzNai+HrTTdWsG5UK+RPp948WemchcMzcpJUAACjz3zGmcmt/Ja65hGSCcW88gjI/+bc0NRZW0XhqtlYOQ2ptmuRV3+678/jMw0ANG7XLbFMZ4HoakldJwrNk9eG/UP4hxO3ozglVj9foJYrU9vJOCwF7Bdcbv5eKAY7e4FDm1GAKgH70jtepozqOUjLlO2YTIIfU5UkYLcn02qazL/8uQbZ6G84DqpF5ZJjpEGj6MV+yjcJ/wKirDPy3mmquq6XySgH9WMERMcj51fjvbvxQxKCwZSPaRuQcJKAUaUQ2DuIFmHgcAdUWIbhKGy9tj7b8VNuB0A9HdHNAzwkRihbALAa74/vuMR5pA=
